# This is an example file to declare a list of authorized nodes and their
# associated provisioning data.

# Hex array must start with 0x otherwise it is treated as a string.

# If method is 3, the UID can be set either directly using 'uid' key or the individual components can be set
# using 'node_uid', 'node_uid_type', 'authenticator_uid', 'authenticator_uid_type' keys. Individual 'uid' key
# takes precedence over the individual components.

# Format is:
# 
# version: 1
# networks:
#   network_name: (mandatory)(string) Ex: test_network
#     address: (mandatory)(uint) Ex: 0x1012EE
#     channel: (mandatory)(uint) Ex: 13
#     authentication_key : (mandatory)(16 bytes string) Ex: 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF
#     encryption_key : (mandatory)(16 bytes string) Ex: 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF
#     
# node_name : (mandatory)(string) Ex: test_node
#    method : (mandatory)(Unsecured:0, Secured:1, Extended UID:3) Ex: 0
#    factory_key : (only for methods 1 and 3)(32 bytes string, [0:15 Auth key][16:31 Enc Key])
#    node_uid : (optional)(16 bytes string) Ex: 0x7e 0x71 0xe5 0xd7 0x22 0xef 0x0f 0x4b 0xa8 0x7d 0x44 0xd4 0xe0 0xe5 0xb5 0x7d
#    node_uid_type : (optional)(1 byte string) Ex: 0x01
#    node_authenticator_uid_type : (optional)(1 byte string) Ex: 0x01
#    node_authenticator_uid : (optional)(16 bytes string) Ex: 0xb3 0x43 0x33 0x00 0x93 0x81 0x08 0x4a 0x8d 0xb3 0xaa 0x9e 0x53 0xd2 0x2a 0x1e
#    uid : (optional)(34 bytes string) Ex: 0x01 0xb3 0x43 0x33 0x00 0x93 0x81 0x08 0x4a 0x8d 0xb3 0xaa 0x9e 0x53 0xd2 0x2a 0x1e 0x01 0x7e 0x71 0xe5 0xd7 0x22 0xef 0x0f 0x4b 0xa8 0x7d 0x44 0xd4 0xe0 0xe5 0xb5 0x7d
#    network : (mandatory)(string) Ex: test_network
#    node_id : (optional)(uint) Ex: 0x11
#    node_role : (optional)(1 byte string) Ex: 0x41
#    user_specific : (optional) indexes [128:255]
#        128 : 'some_string'
#        129 : 0x34


networks:
  network_demo:
    address: 1053422
    authentication_key: '0x0102030405060708090a0b0c0d0e0f10'
    channel: 2
    encryption_key: '0x0102030405060708090a0b0c0d0e0f10'
  network_prod:
    address: 2243501
    authentication_key: '0x100f0e0d0c0b0a090807060504030201'
    channel: 7
    encryption_key: '0x100f0e0d0c0b0a090807060504030201'
nodes:
  test_node_extended:
    authenticator_uid: 0xb3 0x43 0x33 0x00 0x93 0x81 0x08 0x4a 0x8d 0xb3 0xaa 0x9e 0x53 0xd2 0x2a 0x1e
    authenticator_uid_type: 1
    factory_key: 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F
    method: 3
    network: network_prod
    node_id: 17
    node_uid: 0x7e 0x71 0xe5 0xd7 0x22 0xef 0x0f 0x4b 0xa8 0x7d 0x44 0xd4 0xe0 0xe5 0xb5 0x7d
    node_uid_type: 1
  test_node_insecure:
    method: 0
    network: network_demo
    node_id: 17
    uid: 0x41 0xb1 0x85 0x7a 0x0f 0xb6 0xb1 0x48 0xa5 0xe4 0xb9 0xb6 0x03 0x53 0x1b 0x3b
  test_node_secure:
    factory_key: 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F
    method: 1
    network: network_prod
    node_id: 17
    uid: 0x58 0xc8 0x12 0xad 0x37 0xe8 0x36 0x4a 0xa1 0x1f 0x1c 0xbc 0x63 0x3e 0x8e 0x34
  test_node_extended_uuid_only:
    uid: 0x70 0xC8 0x33 0x00 0x00 0x00 0x00 0x00 0x00 0x87 0x00 0x00 0x00 0x00 0x00 0x01 0x01 0x7F 0xC8 0x33 0x00 0x00 0x00 0x00 0x00 0x00 0x87 0x00 0x00 0x00 0x00 0x00 0x01 0x01
    method: 0x03
    network: network_prod
    node_id: 0x05
    factory_key: 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F
    
version: 1
