# This is an example file to declare a list of authorized nodes and their
# associated provisioning data.

# Hex array must start with 0x otherwise it is treated as a string.

# Format is:
#
# UID : (mandatory) Ex: test_node
#    method : (mandatory)(Unsecured:0 or Secured:1) Ex: 0
#    factory_key : (only for secured method)(32 bytes string, [0:15 Auth key][16:31 Enc Key])
#    authentication_key : (mandatory)(16 bytes string) Ex: 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF
#    encryption_key : (mandatory)(16 bytes string) Ex: 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF
#    network_address : (optional)(uint) Ex: 0x1012EE
#    network_channel : (optional)(uint) Ex: 13
#    node_id : (optional)(uint) Ex: 0x11
#    node_role : (optional)(1 byte string) Ex: 0x41
#    user_specific : (optional) indexes [128:255]
#        128 : 'some_string'
#        129 : 0x34

test_node :
    method : 1
    factory_key : 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F
    authentication_key : 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0A 0x0B 0x0C 0x0D 0x0E 0x0F 0x10
    encryption_key : 0x10 0x0F 0x0E 0x0D 0x0C 0x0B 0x0A 0x09 0x08 0x07 0x06 0x05 0x04 0x03 0x02 0x01
    network_address : 0x1012EE
    network_channel : 2
    node_id : 0x11